zen changes to snap kick, and set ammo count
MaxwellJung/ow1_emulator pull request #129
Opened 2023-07-06 21:57 UTC by snappycreeper

fixes #102

2023-07-06 23:20 UTC, MaxwellJung commented on src/constants/ow1_constants.opy
> +# Zenyatta
Can you move zenyatta after zarya?

2023-07-06 23:21 UTC, MaxwellJung commented on src/ow1/heroes/heroes.opy
> +#!include "ow1/heroes/zenyatta.opy"
move zenyatta after zarya

2023-07-06 23:22 UTC, MaxwellJung requested changes
Other than the name ordering, everything looks good, as long as the 50% reduction is correct.

2023-07-07 01:05 UTC, snappycreeper commented
Changed names and fixed the 50% knockback

2023-07-07 02:22 UTC, MaxwellJung approved these changes
Looks good!

2023-07-07 02:22 UTC, merged